### ISSUE TITLE
Umlauts and other special characters add spacing to labels

### ISSUE THREAD

**Issue by pasipasi123** [wilkelab/ggtext#19] opened 2020-02-10 11:08 UTC
My native language has a lot of umlauts so I came across this bug. Using the provided example (rendering a reprex is also impossible for some reason):

```
library(ggplot2)
library(ggtext)

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 3) +
  scale_color_manual(
    name = NULL,
    values = c(setosa = "#0072B2", virginica = "#009E73", versicolor = "#D55E00"),
    labels = c(
      setosa = "<i style='color:#0072B2'>I. setosa</i>",
      virginica = "<i style='color:#009E73'>I. virginica</i>",
      versicolor = "<i style='color:#D55E00'>I. versicolor</i>")
  ) +
  labs(
    title = "**Fisher's *Iris* úúúúú dataset**  
    <span style='font-size:11pt'>Sepal width vs. sepal length ääääää for three *Iris*
    species</span>",
    x = "Sepal length (cm)", y = "Sepal width (cm)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_markdown(lineheight = 1.1),
    legend.text = element_markdown(size = 11)
  )
```
![image](https://user-images.githubusercontent.com/34722481/74144774-070c9000-4c06-11ea-9f8d-97099ce4aa3a.png)

**Comment by clauswilke** [comment] 2020-02-10 17:34
I can't reproduce this. Are you using Windows? Can you try a different graphics device (e.g., pdf)?

``` r
library(ggplot2)
library(ggtext)

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 3) +
  scale_color_manual(
    name = NULL,
    values = c(setosa = "#0072B2", virginica = "#009E73", versicolor = "#D55E00"),
    labels = c(
      setosa = "<i style='color:#0072B2'>I. setosa</i>",
      virginica = "<i style='color:#009E73'>I. virginica</i>",
      versicolor = "<i style='color:#D55E00'>I. versicolor</i>")
  ) +
  labs(
    title = "**Fisher's *Iris* úúúúú dataset**  
    <span style='font-size:11pt'>Sepal width vs. sepal length ääääää for three *Iris*
    species</span>",
    x = "Sepal length (cm)", y = "Sepal width (cm)"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_markdown(lineheight = 1.1),
    legend.text = element_markdown(size = 11)
  )
```

![](https://i.imgur.com/j73itwp.png)

<sup>Created on 2020-02-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment] 2020-02-10 17:35
Also, do the umlauts in the title and caption render correctly if you're not using `element_markdown()`?

**Comment by pasipasi123** [comment] 2020-02-11 09:23
Yes, Windows, and the behavior is the same on two different Windows machines. I copied the image file a posted above from Rstudio's Plots window. If I save the plot to a file, pdf or png, the text displays just fine!

![image](https://user-images.githubusercontent.com/34722481/74224039-ae4dfd80-4cc0-11ea-8216-2c8d12ff30f4.png)

**Comment by clauswilke** [comment] 2020-02-11 14:15
Ok, that's what I thought. The Windows graphics device is known to have issues.

Could you run the following two examples and post the output from RStudio's plot windows?

``` r
library(ggplot2)

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 3) +
  scale_color_manual(
    name = NULL,
    values = c(setosa = "#0072B2", virginica = "#009E73", versicolor = "#D55E00"),
    labels = c(
      setosa = "úúúúú",
      virginica = "äääää",
      versicolor = "aaaaa")
  ) +
  theme_minimal()
```

![](https://i.imgur.com/i4T678s.png)

``` r

ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
  geom_point(size = 3) +
  scale_color_manual(
    name = NULL,
    values = c(setosa = "#0072B2", virginica = "#009E73", versicolor = "#D55E00"),
    labels = c(
      setosa = "aaaaa",
      virginica = "aaaaa",
      versicolor = "aaaaa")
  ) +
  theme_minimal()
```

![](https://i.imgur.com/CMH2G89.png)

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment] 2020-02-11 14:16
Specifically, is the spacing to the right of the legend the same in both cases?

**Comment by clauswilke** [comment] 2020-10-11 17:34
Closing this, as it is a graphics device issue.

**Closed by clauswilke** 2020-10-11 17:34 UTC
